import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "@/styles/globals.css";
import AppProvider from "@/providers";

const archivo = Archivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Gantries",
    template: "%s | Gantries",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.className}`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
